=== cr8onski/statement-schema/statement.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Schema for an xAPI Statement",
    "id":"http://localhost:8080/statements-schema.json",

    "type": "object",

    "required": ["actor", "verb", "object"],

    "additionalProperties": false,

    "properties": {
        "id": { "$ref": "#/definitions/uuid" },
        "actor": { "$ref": "#/definitions/actor" },
        "verb" : { "$ref": "#/definitions/verb" },
        "object": {"type": "object"},
        "result": { "$ref": "#/definitions/result" },
        "context": { "$ref": "#/definitions/context" },
        "timestamp": {
            "type": "string",
            "format": "date-time"
        },
        "stored": {
            "type": "string",
            "format": "date-time"
        },
        "authority": {"type": "object"},
        "version": {
            "type": "string",
            "pattern": "^1.0.[0-9]+$"
        },
        "attachments": {"type": "array"}
    },

    "definitions": {
        "iri": {
            "type": "string",
            "pattern": "^[\\S]+:\\/\\/?(?!\\/)[\\S]+$"
        },
        "uuid": {
            "type": "string",
            "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
        },
        "lang-map": {
            "type": "object",
            "patternProperties": {
                "^[a-z]{2,3}(?:-[A-Z]{2,3}(?:-[a-zA-Z]{4})?)?$": { "type": "string" }
            },
            "additionalProperties": false
        },
        "actor": {
            "allOf": [
                { "$ref": "#/definitions/base-actor" }
            ],
            "oneOf": [
                { "$ref": "#/definitions/agent"},
                { "$ref": "#/definitions/group"}
            ]
        },
        "base-actor": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "agent": {
            "type": "object",
            "properties": {
                "objectType": {
                    "type": "string",
                    "pattern": "Agent"
                }
            },
            "allOf": [
                {"$ref":"#/definitions/ifi"}
            ],
            "oneOf": [
                { "required": ["mbox"] },
                { "required": ["mbox_sha1sum"] },
                { "required": ["openid"] },
                { "required": ["account"] }
            ]
        },
        "group": {
            "type": "object",
            "properties": {
                "objectType": {
                    "type": "string",
                    "pattern": "Group"
                }
            },
            "required": ["objectType"]
        },
        "ifi": {
            "oneOf": [
                { "$ref": "#/definitions/mbox" },
                { "$ref": "#/definitions/mbox_sha1sum" },
                { "$ref": "#/definitions/openid" },
                { "$ref": "#/definitions/account" }
            ]
        },
        "mbox": {
            "properties": {
                "mbox": {
                    "type": "string",
                    "pattern": "mailto:\\S+@\\S+\\.\\S+"
                }
            },
            "required": ["mbox"]
        },
        "mbox_sha1sum": {
            "properties": {
                "mbox_sha1sum": {
                    "type": "string"
                }
            },
            "required": ["mbox_sha1sum"]
        },
        "openid": {
            "properties": {
                "openid": { "$ref": "#/definitions/iri" }
            },
            "required": ["openid"]
        },
        "account": {
            "properties": {
                "account": {
                    "type": "object",
                    "properties": {
                        "homePage": { "$ref": "#/definitions/iri" },
                        "name": {
                            "type": "string"
                        }
                    },
                    "required": [ "homePage", "name" ]
                }
            },
            "required": [ "account" ]
        },
        "verb": {
            "properties": {
                "id": { "$ref": "#/definitions/iri" },
                "display": { "$ref": "#/definitions/lang-map" }
            },
            "required": [ "id" ],
            "additionalProperties": false
        },
        "object": {},
        "activity": {
            "type": "object",
            "properties": {
                "objectType": {
                    "type": "string",
                    "pattern": "Activity"
                },
                "id": { "$ref": "#/definitions/iri" },
                "definition": { "$ref": "#/definitions/activity-definition" }
            },
            "required": [ "id" ],
            "additionalProperties": false
        },
        "activity-definition": {
            "type": "object",
            "properties": {
                "name": { "$ref": "#/definitions/lang-map" },
                "description": { "$ref": "#/definitions/lang-map" },
                "type": { "$ref": "#/definitions/iri" },
                "moreInfo": { "$ref": "#/definitions/iri" },
                "interactionType": {
                    "enum": [
                        "true-false",
                        "choice",
                        "fill-in",
                        "long-fill-in",
                        "matching",
                        "performance",
                        "sequencing",
                        "likert",
                        "numeric",
                        "other"
                    ]
                },
                "correctResponsesPattern": {
                    "type": "array",
                    "items": { "type": "string" }
                },
                "choices": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/interactionComponent" }
                },
                "scale": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/interactionComponent" }
                },
                "source": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/interactionComponent" }
                },
                "target": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/interactionComponent" }
                },
                "steps": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/interactionComponent" }
                }
            },
            "additionalProperties": false
        },
        "interactionComponent": {
            "type": "object",
            "properties": {
                "id": { "type": "string" },
                "description": { "$ref": "#/definitions/lang-map" }
            },
            "required": [ "id" ],
            "additionalProperties": false
        },
        "result": {
            "type": "object",
            "properties": {
                "score": { "$ref": "#/definitions/score" },
                "success": { "type": "boolean" },
                "completion": { "type": "boolean" },
                "response": { "type": "string" },
                "duration": {
                    "type": "string",
                    "pattern": "^P(?=\\w*\\d)(?:\\d+Y|Y)?(?:\\d+M|M)?(?:\\d+W|W)?(?:\\d+D|D)?(?:T(?:\\d+H|H)?(?:\\d+M|M)?(?:\\d+(?:\\Â­.\\d{1,2})?S|S)?)?$"
                },
                "extensions": { "$ref": "#/definitions/extensions" }
            },
            "additionalProperties": false
        },
        "score": {
            "type": "object",
            "properties": {
                "scaled": {
                    "type": "number",
                    "minimum": -1,
                    "maximum": 1
                },
                "raw": { "type": "number" },
                "min": { "type": "number" },
                "max": { "type": "number" }
            },
            "additionalProperties": false
        },
        "extensions": {
            "type": "object",
            "patternProperties": {
                "^[\\S]+:\\/\\/?(?!\\/)[\\S]+$": { "type": "string" }
            },
            "additionalProperties": false
        },
        "context": {
            "type": "object",
            "properties": {
                "registration": { "$ref": "#/definitions/uuid" },
                "instructor": { "$ref": "#/definitions/actor" },
                "team": { "$ref": "#/definitions/group" },
                "contextActivities": { "$ref": "#/definitions/contextActivities" },
                "revision": { "type": "string" },
                "platform": { "type": "string" },
                "language": {
                    "type": "string"
                },
                "statement": { "$ref": "#/definitions/statementRef" },
                "extensions": { "$ref": "#/definitions/extensions" }
            },
            "additionalProperties": false
        },
        "contextActivities": {
            "type": "object",
            "properties": {
                "parent": {
                    "oneOf": [
                        {"$ref": "#/definitions/arrayOfActivities" },
                        {"$ref": "#/definitions/activity" }
                    ]
                },
                "grouping": {
                    "oneOf": [
                        {"$ref": "#/definitions/arrayOfActivities" },
                        {"$ref": "#/definitions/activity" }
                    ]
                },
                "category": {
                    "oneOf": [
                        {"$ref": "#/definitions/arrayOfActivities" },
                        {"$ref": "#/definitions/activity" }
                    ]
                },
                "other": {
                    "oneOf": [
                        {"$ref": "#/definitions/arrayOfActivities" },
                        {"$ref": "#/definitions/activity" }
                    ]
                }
            },
            "additionalProperties": false
        },
        "arrayOfActivities": {
            "type": "array",
            "items": { "$ref": "#/definitions/activity" }
        },
        "statementRef": {
            "type": "object",
            "properties": {
                "objectType": {
                    "type": "string",
                    "pattern": "StatementRef"
                },
                "id": { "$ref": "#/definitions/uuid" }
            },
            "additionalProperties": false
        }
    }
}

=== cr8onski/statement-schema/statements/various.json
{
    "id":"f5070c3a-cd39-4dc3-8dd2-4ad3b511c407",
    "actor":{"mbox":"mailto:tom@example.com", "name":"andy", "objectType":"Agent"},
    "verb":{"id":"http://tom.com/verb", "display":{"en":"hi"}},
    "object": {"id":"http://tom.com/obj"},
    "version":"1.0.2",
    "timestamp":"2017-03-23T21:14:21.690Z",
    "stored":"2017-03-23T21:14:45.282Z"
}

=== cr8onski/statement-schema/test/statements/timestamps/timestampStored.json
{
    "actor":{"mbox":"mailto:tom@example.com"},
    "verb":{"id":"http://tom.com/verb", "display": {"en-GB-oed":"runneth"}},
    "object": {"id":"http://tom.com/obj"},
    "timestamp": "2017-02-31T20:53:06.892Z",
    "stored": "2017-02-31t20:53:06.010z",
    "id": "12345678-1234-1234-9234-1234567890ab"
}
